services:
  - type: web
    name: traderblock-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8003
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 8003
