services:
  - type: web
    name: traderblock-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: DEFAULT_ALPACA_KEY
        sync: false
      - key: DEFAULT_ALPACA_SECRET
        sync: false
      - key: GNEWS_API_KEY
        sync: false
